name: Publish to npm

on: 
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm build

      - name: Publish package
        run: npm publish

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

   